[package]
name = "librunner"
version = "0.1.0"
edition = "2021"
license = " Apache-2.0 license"
description = "Rust library to assist runners on planning their workouts, races, and improve their health."
repository = "https://github.com/geekrunners/librunner"

[dependencies]